use_frameworks!

platform :ios, '10.0'

target 'VolWebProJSBridge_Example' do
  pod 'VolWebProJSBridge', :path => '../'

  target 'VolWebProJSBridge_Tests' do
    inherit! :search_paths

    
  end
end
